name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the information below.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported
          required: true
        - label: I have read the [documentation](https://teyk0o.github.io/pontos/)
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. With parameters '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      placeholder: Describe expected behavior...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened?
      placeholder: Describe actual behavior...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error logs
      description: Paste any relevant error messages or logs
      render: shell
      placeholder: |
        Traceback (most recent call last):
          ...

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux
        - macOS
        - Windows
        - Docker
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python version
      placeholder: "3.12.0"
    validations:
      required: true

  - type: dropdown
    id: device
    attributes:
      label: Computation device
      options:
        - CPU
        - NVIDIA GPU (CUDA)
        - AMD GPU (ROCm)
    validations:
      required: true

  - type: input
    id: pontos-version
    attributes:
      label: Pontos version
      description: Run `pip show pontos` or check `pontos/__init__.py`
      placeholder: "0.1.0"

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other context about the problem
      placeholder: Screenshots, configuration files, etc.
