name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested
          required: true
        - label: I have read the [documentation](https://teyk0o.github.io/pontos/)
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem does this feature solve? What's your use case?
      placeholder: |
        I'm trying to do X but currently...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the solution you'd like
      placeholder: |
        I would like to be able to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: |
        I've tried...

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of Pontos does this relate to?
      options:
        - CLI
        - Detector (YOLO)
        - Sentinel Hub integration
        - GeoJSON export
        - Configuration
        - Docker
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Important
        - Critical for my use case

  - type: textarea
    id: use-cases
    attributes:
      label: Use cases
      description: Describe concrete scenarios where this feature would be useful
      placeholder: |
        1. Maritime surveillance teams could use this to...
        2. Research applications would benefit from...

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other context, mockups, screenshots, or references
      placeholder: |
        - Links to similar implementations
        - Mockups or diagrams
        - Related papers or documentation

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Let us know if you'd like to help implement this feature
      options:
        - label: I'm willing to submit a pull request for this feature
